config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  get 'terms', to: 'application#terms'
  get 'impressum', to: 'application#impressum'
  get 'privacy', to: 'application#privacy'
  get 'contact', to: 'application#contact'
  post 'contact', to: 'application#send_contact', as: 'send_contact'

  devise_for :users, path: "", controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }, path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'register', 
    sign_up: '' 
  }
  
  get '/logout', to: 'users/sessions#destroy '
  
  get '/account', to: 'users#account'
  post '/account', to: 'users#update_account', as: 'update_account'
  get '/account/settings', to: 'users/registrations#edit'
  post '/account/settings', to: 'users/registrations#update', as: 'update_account_settings'
    
    
  resources :games
  
  resources :users, only: [:index, :show] do
    resources :games, only: [:index, :show]
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user
    
    validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
  add_breadcrumb :root
  
  def index
  end
  
  def terms
    add_breadcrumb :terms
  end
  
  def impressum
    add_breadcrumb :impressum
  end
  
  def privacy
    add_breadcrumb :privacy
  end
  
  def contact
    add_breadcrumb :contact
  end
  
  def send_contact
    sender = {name: params[:name], email: params[:email], message: params[:message]}
    ContactMailer.contact_mail(sender).deliver
    redirect_to :back, :notice => "Mail Sent. We will read your mail as soon as possible!"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]
  
  def index
    if @user
      @games = @user.games
    else
      @games = Game.all
    end
  end
  
  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new game_params
    if @game.save
      redirect_to game_path @game, status: 301
    else
      redirect_to :back
    end
  end

  def show
  end
  
  def edit
  end
  
  def update
    if @game.update_attributes game_params
      redirect_to game_path @game, status: 301
    else
      redirect_to :back
    end
  end
  
  def destroy
    @game.destroy
    redirect_to games_path
  end
  
  private
    def set_game
      @game = Game.find params[:id]
    end
    
    def set_user
      if params[:user_id]
        @user = User.find params[:user_id]
      end
    end

    def game_params
      params.permit!
      params[:game]
    end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  def new
    add_breadcrumb :register
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    add_breadcrumb :login
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show]
    
    def index
      @users = User.all
    end
    
    def show
      add_breadcrumb :profile
    end
    
    def account
      add_breadcrumb :account
    end
    
    private
      def set_user
        @user = User.find params[:id]
      end
  
      def user_params
        params.permit!
        params[:user]
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def app_version
    end
    
    def copyright
        "&copy; 2015 Tea Party Network"
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/contact.html.erb
<div class="row">
    <div class="col-md-12">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6306.723438082578!2d-122.39844028870407!3d37.78156193197657!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8085807e0fbb1b7b%3A0xed3852393ecfd4be!2s795+Folsom+St+%23600%2C+San+Francisco%2C+CA+94107%2C+USA!5e0!3m2!1sde!2sde!4v1421225586862" width="100%" height="200" frameborder="0" style="border:0"></iframe>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <%= form_tag(send_contact_path, method: :post, class: "form-horizontal") do %>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <h2>Get in touch</h2>
                </div>
            </div>
            
            <div class="form-group">
                <%= label_tag 'name', nil, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag 'name', nil, autofocus: true, class: "form-control", :placeholder => "Your Name" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= label_tag 'email', nil, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= email_field_tag 'email', nil, class: "form-control", :placeholder => "Your Email" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= label_tag 'message', nil, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_area_tag 'message', nil, rows: 5, class: "form-control", :placeholder => "Your Message" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= submit_tag "Send", class: "btn btn-default" %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-3">
        <h2>Infos</h2>
        
        <address>
            <strong>damncraft</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
        
        <address>
            <strong>Damn Crafte</strong><br>
            <a href="mailto:bishojo@damncraft.com">bishojo@damncraft.com</a>
        </address>
    </div>
</div>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'shared/layouts/head' %>
  </head>
  <body class="metro">
    <%= render 'shared/layouts/header' %>
    <%= render 'shared/layouts/body' %>
    <%= render 'shared/layouts/footer' %>
  </body>
</html>

app/views/shared/layouts/_body.html.erb
<div class="main-content clearfix">
    <%= render 'shared/layouts/body/notice' %>
    <%= yield %>
</div>

app/views/shared/layouts/_footer.html.erb
<footer>
    <%= render 'shared/layouts/footer/footer_nav' %>
</footer>

app/views/shared/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Bishojo" %></title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag "application", :media => "all" %>

<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

<%= javascript_include_tag "application" %>

app/views/shared/layouts/_header.html.erb
<header>
    <%= render 'shared/layouts/header/main_nav' %>
</header>

app/views/shared/layouts/body/_notice.html.erb
<%= bootstrap_flash %>

app/views/shared/layouts/footer/_copyright.html.erb
<div class="element">
    <span>
        <%= t('copyright').html_safe %>
    </span>
</div>

app/views/shared/layouts/footer/_footer_nav.html.erb
<nav class="navigation-bar white fixed-bottom shadow">
    <nav class="navigation-bar-content container">
        <%= render 'shared/layouts/footer/copyright' %>
    </nav>
</nav>

app/views/shared/layouts/header/_brand_in_main_nav.html.erb
<%= link_to root_path, {:class => 'element brand', :title => t('bishojo_title')} do %>
    <%= t('bishojo') %>
<% end %>

app/views/shared/layouts/header/_main_nav.html.erb
<nav class="navigation-bar white fixed-top shadow">
    <nav class="navigation-bar-content container">
        <%= render 'shared/layouts/header/brand_in_main_nav' %>
        <span class="element-divider"></span>
        
        <%= render 'shared/layouts/header/reloader_in_main_nav' %>
        <span class="element-divider"></span>

        <%= render 'shared/layouts/header/search_in_main_nav' %>
        
        <!-- RIGHT MENU ITEMS -->
        <%= render 'shared/layouts/header/settings_in_main_nav' %>
        <span class="element-divider place-right"></span>
        
        <%= render 'shared/layouts/header/user_in_main_nav' %>
        <span class="element-divider place-right"></span>
        
        <%= render 'shared/layouts/header/admin_in_main_nav' %>
        <span class="element-divider place-right"></span>
    </nav>
</nav>

app/views/shared/layouts/header/_reloader_in_main_nav.html.erb
<a class="element brand" href="#" title="<%= t('reload_page') %>">
    <span class="icon-spin"></span>
</a>

app/views/shared/layouts/header/_search_in_main_nav.html.erb
<div class="element input-element">
    <form>
        <div class="input-control text">
            <input type="text" placeholder="<%= t('search') %>...">
            <button class="btn-search"></button>
        </div>
    </form>
</div>

app/views/shared/layouts/header/_settings_in_main_nav.html.erb
<div class="element place-right">
    <a class="dropdown-toggle" href="#">
        <span class="icon-cog"></span>
    </a>
    <ul class="dropdown-menu place-right" data-role="dropdown">
        <li><a href="#">Products</a></li>
        <li><a href="#">Download</a></li>
        <li><a href="#">Support</a></li>
        <li><a href="#">Buy Now</a></li>
    </ul>
</div>

app/views/shared/layouts/header/_user_in_main_nav.html.erb
<% if(user_signed_in?) %>

<% else %>

    <%= link_to new_user_registration_path, {:class => 'element place-right'} do %>
        <span class="icon-user-3"></span>
        <%= t('sign_up') %>
    <% end %>
    
    <span class="element-divider place-right"></span>
    
    <%= link_to new_user_session_path, {:class => 'element place-right'} do %>
        <span class="icon-key"></span>
        <%= t('sign_in') %>
    <% end %>
    
<% end %>

app/views/users/account.html.erb
<h1>Users#account</h1>
<p>Find me in app/views/Users/account.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/Users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/Users/show.html.erb</p>